# Potsgres
default:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['DB_USERNAME'] >
  password: <%= ENV['DB_PASSWORD'] >
  host: localhost

development:
  <<: *default
  database: cryptozaurous_rex_development
test:
  <<: *default
  database: cryptozaurous_rex_test

production:
  <<: *default
  database: cryptozaurous_rex_production
